/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dominio.Area;
import dominio.Empleado;
import dominio.Sistema;
import java.awt.Color;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class VentanaReporteEstadoAreas extends javax.swing.JFrame implements PropertyChangeListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReporteEstadoAreas.class.getName());

    private Sistema s;
    private ArrayList<Area> listaAreas;

    public VentanaReporteEstadoAreas() {
        initComponents();
    }

    public VentanaReporteEstadoAreas(Sistema sistema) {
        initComponents();
        this.s = sistema;
        s.agregarListener(this);
        pnlAreas.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        pnlEmpleados.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        cargarAreas();
    }

    @Override
    public void propertyChange(java.beans.PropertyChangeEvent evt) {
        cargarAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAreaSeleccionada = new javax.swing.JLabel();
        pnlEmpleados = new javax.swing.JPanel();
        pnlAreas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de el estado de las Areas");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        lblAreaSeleccionada.setBackground(new java.awt.Color(255, 204, 0));
        lblAreaSeleccionada.setForeground(new java.awt.Color(255, 255, 255));
        lblAreaSeleccionada.setText("Area:");
        lblAreaSeleccionada.setOpaque(true);

        pnlEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        javax.swing.GroupLayout pnlEmpleadosLayout = new javax.swing.GroupLayout(pnlEmpleados);
        pnlEmpleados.setLayout(pnlEmpleadosLayout);
        pnlEmpleadosLayout.setHorizontalGroup(
            pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlEmpleadosLayout.setVerticalGroup(
            pnlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAreaSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAreaSeleccionada)
                .addGap(28, 28, 28)
                .addComponent(pnlEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAreas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Areas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 204, 0))); // NOI18N
        pnlAreas.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout pnlAreasLayout = new javax.swing.GroupLayout(pnlAreas);
        pnlAreas.setLayout(pnlAreasLayout);
        pnlAreasLayout.setHorizontalGroup(
            pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        pnlAreasLayout.setVerticalGroup(
            pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaReporteEstadoAreas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAreaSeleccionada;
    private javax.swing.JPanel pnlAreas;
    private javax.swing.JPanel pnlEmpleados;
    // End of variables declaration//GEN-END:variables

    private void cargarAreas() {
        pnlAreas.removeAll();
        ArrayList<Area> areas = s.getAreas();
        areas.sort(Comparator.comparingDouble(Area::getPorcentajeAsignado).reversed());
        for (Area area : areas) {
            JButton btnArea = new JButton(area.getNombre());
            btnArea.setBackground(getColorPorcentaje(area.getPorcentajeAsignado()));
            btnArea.setForeground(Color.WHITE);

            btnArea.addActionListener(e -> mostrarEmpleadosDeArea(area));

            pnlAreas.add(btnArea);
        }
        pnlAreas.setLayout(new java.awt.GridLayout(0, 1));
        pnlAreas.revalidate();
        pnlAreas.repaint();
    }

    private Color getColorPorcentaje(double porcentaje) {
        if (porcentaje > 90) {
            return Color.RED;
        } else if (porcentaje >= 70) {
            return Color.YELLOW;
        } else {
            return Color.LIGHT_GRAY;
        }
    }
    
    private void mostrarEmpleadosDeArea(Area area) {
    pnlEmpleados.removeAll();
    int porcentajeRedondeado = (int) Math.round(area.getPorcentajeAsignado());
    lblAreaSeleccionada.setText("Área: " + area.getNombre() + " - " + porcentajeRedondeado + "% Asignado");
    pnlEmpleados.removeAll();
    ArrayList<Empleado> empleados = area.getLst_empleados();
    empleados.sort(Comparator.comparing(Empleado::getNombre));
    if (empleados.isEmpty()) {
        pnlEmpleados.add(new javax.swing.JLabel("No hay empleados en esta área"));
    } else {
        double minSalario = empleados.stream().mapToDouble(Empleado::getSalario_mensual).min().orElse(0);
        double maxSalario = empleados.stream().mapToDouble(Empleado::getSalario_mensual).max().orElse(1);

        for (Empleado empleado : empleados) {
            JButton btnEmpleado = new JButton(empleado.getNombre());

            double t = (empleado.getSalario_mensual() - minSalario) / (maxSalario - minSalario + 0.0001); // para evitar división por 0
            int blue = (int) (50 + t * 205);
            int red  = 0;
            int green = 0;
            btnEmpleado.setBackground(new Color(red, green, blue));
            btnEmpleado.setForeground(Color.WHITE);
            btnEmpleado.addActionListener(e -> mostrarInfoEmpleado(empleado));
            pnlEmpleados.add(btnEmpleado);
        }
    }
    pnlEmpleados.revalidate();
    pnlEmpleados.repaint();
}

    private void mostrarInfoEmpleado(Empleado empleado) {
        String info = String.format("Nombre: %s\nCI: %s\nSalario: $%.2f\nÁrea: %s\nManager: %s",
                empleado.getNombre(), empleado.getCi(), empleado.getSalario_mensual(),
                empleado.getArea() != null ? empleado.getArea().getNombre() : "Sin área",
                empleado.getManager() != null ? empleado.getManager().getNombre() : "Sin manager");

        JOptionPane.showMessageDialog(this, info, "Información del empleado", JOptionPane.INFORMATION_MESSAGE);
    }

}
